# Generated by Django 2.2.4 on 2019-08-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=255)),
                ('raise_user', models.IntegerField()),
                ('raise_time', models.DateTimeField()),
                ('solve_user', models.IntegerField()),
                ('solve_time', models.DateTimeField()),
                ('remark', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Problem',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('isSupperuser', models.IntegerField()),
                ('role', models.IntegerField()),
                ('remark', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
