# Generated by Django 2.2.4 on 2019-08-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('isSupperuser', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('static_balance', models.IntegerField(default=0)),
                ('static_blocked_balance', models.IntegerField(default=0)),
                ('dynamic_balance', models.IntegerField(default=0)),
                ('jiayuan_coin', models.IntegerField(default=5)),
                ('superior_phone', models.BigIntegerField(default=0)),
                ('id_card', models.BigIntegerField()),
                ('bank_card', models.IntegerField()),
                ('alipay_id', models.CharField(max_length=20)),
                ('pay_pwd', models.CharField(max_length=20)),
                ('is_first', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
